apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkamoon-api
spec:
  selector:
    matchLabels:
      app: kafkamoon-api
  template:
    metadata:
      labels:
        app: kafkamoon-api
    spec:
      containers:
      - name: kafkamoon-api
        image: {{ .Values.kafkamoon.image }}
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: kafkamoon.default.svc.cluster.local:9092
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: {{ .Values.kafkamoon.port }}
        livenessProbe:
          httpGet:
            path: "/actuator/health/liveness"
            port: {{ .Values.kafkamoon.port }}
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: "/actuator/health/readiness"
            port: {{ .Values.kafkamoon.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
          