spring:
  application:
    name: kafkamoon-api
server:
  port: 8888


kafkamoon:
  kafka:
    bootstrap:
      servers: localhost:9092
  docs:
    url: http://localhost:3000
    topic-name-exceeded-limit: ${kafkamoon.docs.url}/#/reference/api?id=topic-name-exceeded-limit
    invalid-request: ${kafkamoon.docs.url}/#/reference/api?id=invalid-request
    topic-with-conflict: ${kafkamoon.docs.url}/#/reference/api?id=topic-with-conflict

