apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkamoon-api
spec:
  selector:
    matchLabels:
      app: kafkamoon-api
  template:
    metadata:
      labels:
        app: kafkamoon-api
    spec:
      replicas: 2
      containers:
      - name: kafkamoon-api
        image: {{ .Values.kafkamoon.api.image }}
        env:
        - name: KEYCLOAK_ISSUER_ID
          value: http://{{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local/realms/kafkamoon
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Release.Name }}-controller-headless.{{ .Release.Namespace }}.svc.cluster.local:9092,{{ .Release.Name }}-controller-headless.{{ .Release.Namespace }}.svc.cluster.local:9093,{{ .Release.Name }}-controller-headless.{{ .Release.Namespace }}.svc.cluster.local:9094"
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: {{ .Values.kafkamoon.api.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: 'kafkamoon-api'
spec:
  type: LoadBalancer
  selector:
    app: 'kafkamoon-api'
  ports:
  - name: "http"
    port: 80
    targetPort: 8080
