apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkamoon-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafkamoon-api
  template:
    metadata:
      labels:
        app: kafkamoon-api
    spec:
      containers:
      - name: kafkamoon-api
        image: {{ .Values.kafkamoon.api.image }}
        env:
        - name: KEYCLOAK_ISSUER_URI
          value: https://keycloak.platformoon.com/realms/kafkamoon
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:9092"
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.kafkamoon.mode }}
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: {{ .Values.kafkamoon.api.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: 'kafkamoon-api'
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-tls-cert: arn:aws:acm:{{ .Values.kafkamoon.awsRegion }}:{{ .Values.kafkamoon.awsAccount }}:certificate/{{ .Values.kafkamoon.api.tls.acm }}
    service.beta.kubernetes.io/aws-load-balancer-tls-ports: "https"
spec:
  type: LoadBalancer
  selector:
    app: 'kafkamoon-api'
  ports:
  - name: "http"
    port: 80
    targetPort: {{ .Values.kafkamoon.api.port }}
  - name: "https"
    port: 443
    targetPort: {{ .Values.kafkamoon.api.port }}
