apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkamoon-docs
spec:
  selector:
    matchLabels:
      app: kafkamoon-docs
  template:
    metadata:
      labels:
        app: kafkamoon-docs
    spec:
      containers:
      - name: kafkamoon-docs
        image: {{ .Values.kafkamoon.docs.image }}
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: {{ .Values.kafkamoon.docs.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: 'kafkamoon-docs'
spec:
  type: LoadBalancer
  selector:
    app: 'kafkamoon-docs'
  ports:
  - name: "http"
    port: 80
    targetPort: 3000
