kafkamoon:
  api:
    port: 8080
    image: docker pull matheuscruzdev/kafkamoon-api:v0.1.0-test.5
  docs:
    port: 3000
    image: docker.io/matheuscruzdev/kafkamoon-docs:main
  certificates:
    api:
    docs:

# grafana operator
grafana-operator:
  enabled: true
  grafana:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
        service.beta.kubernetes.io/aws-load-balancer-tls-cert:
        service.beta.kubernetes.io/aws-load-balancer-tls-ports: "https"
      extraPorts: 
        - port: 443
          name: "https"
          targetPort: 3000
      type: "LoadBalancer"
  commonLabels:
    dashboards: "grafana"

# bitnami/kafka configuration
kafka:
  enabled: true
  extraConfigs:
    deleteTopicEnable: true
    autoCreateTopicsEnable: false 
  volumePermissions:
    enabled: true
  controller:
    replicaCount: 2
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
  metrics:
    zookeeper:
      metrics: 
        enabled: true
    kafka:
      enabled: true
    jmx:
      enabled: true

prometheus:
  enabled: true
  alertmanager:
    service:
      type: "ClusterIP"
  server:
    configuration: |
      scrape_configs:
        - job_name: 'kafkamoon-api-metrics'
          metrics_path: '/actuator/prometheus'
          scrape_interval: 5s
          static_configs:
            - targets:  ['kafkamoon-api.default.svc.cluster.local:80']
              labels: 
                application: 'kafkamoon-api'
        - job_name: 'kafkamoon-kafka-jmx'
          metrics_path: '/metrics'
          scrape_interval: 5s
          static_configs:
            - targets: ['kafkamoon-jmx-metrics.default.svc.cluster.local:5556']
              labels:
                application: 'kafka-jmx'
        - job_name: 'kafkamoon-kafka'
          metrics_path: '/metrics'
          scrape_interval: 5s
          static_configs:
            - targets: ['kafkamoon-metrics.default.svc.cluster.local:9308']
              labels:
                application: 'kafka'
