name: Kafkamoon Continuous Integration

on: push

jobs:
  formatter:
    runs-on: ubuntu-latest
    name:  Run spotless:check
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check formatter
        run: mvn -f pom.xml verify -DskipTests
      - name: Run mvn clean test
        run: mvn -f pom.xml clean test
      - name: Run mvn clean package -DskipTests
        run: mvn -f pom.xml clean package
