name: Kafkamoon Continuous Integration

on:
  push:
    paths-ignore:
      - "terraform-gitops/**"
jobs:
  ci:
    runs-on: ubuntu-latest
    name: Run CI pipeline
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check formatter
        run: mvn -f pom.xml spotless:check

      - name: Test
        run: mvn -f pom.xml clean test

      - name: Package application
        run: mvn -f pom.xml clean package -DskipTests

      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        if: startsWith(github.ref, 'refs/tags/v')
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: matheuscruzdev/kafkamoon-api

      - name: Build and push Docker image
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
