name: Terraform GitOps Apply

on:
  push:
    branches:
      - "main"
    paths:
      - "terraform-gitops/**"
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Run Terraform pipeline
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Terraform init
        run: terraform -chdir=terraform-gitops init
      - name: Terraform apply
        # if: false
        id: apply
        run: terraform -chdir=terraform-gitops apply --auto-approve
